### ISSUE TITLE
When can I update to a newer version?

### ISSUE THREAD

**Issue by lmw17009** [Laex/Delphi-OpenCV#139] opened 2020-11-15 04:30 UTC
I hope opencv can be updated to a higher version. Come on! I always want to carry out OpenCV image recognition project on delphixe, because the currently supported version is relatively old, I am hesitant. If we start now, we need to change a lot of things later.

**Comment by Laex** [comment] 2021-03-12 12:01
I seem to have found a way (simple enough) to make an interface to C ++ classes for x64 and OpenCV 4.5.1.
Now I'm testing ...

Duplicate of #138
Duplicate of #136
Duplicate of #102
Duplicate of #35

**Comment by iga2iga** [comment] 2021-03-12 22:04
Waiting too...

**Comment by salvadordf** [comment] 2021-04-09 08:09
Great news!

**Comment by chris9672** [comment] 2021-04-28 12:38
This is really great news, we are all waiting for a new release from you

**Comment by blaisexen** [comment] 2021-04-28 14:01
> I seem to have found a way (simple enough) to make an interface to C ++ classes for x64 and OpenCV 4.5.1.
> Now I'm testing ...
> 
> Duplicate of #138
> Duplicate of #136
> Duplicate of #102
> Duplicate of #92
> Duplicate of #35

I thought it can only use OpenCV 3.plusplus for c only, but now C ++ classes for x64 and OpenCV 4.5.1.
that's so good, really good

I have tested using OpenCV 3.plusplus with lots of debugs from the original lines of code and runs good, except for some other functions I didn't include, anyway it's just a test for me, I still didn't use it because I'm not sure it's gonna work a long while.

but with regards to the matters you said , WOW so cool, because of you DELPHI is so grateful, I hope Embarcadero see you

**Comment by chris9672** [comment] 2021-06-29 17:15
> 
> 
> I seem to have found a way (simple enough) to make an interface to C ++ classes for x64 and OpenCV 4.5.1.
> Now I'm testing ...
> 
> Duplicate of #138
> Duplicate of #136
> Duplicate of #102
> Duplicate of #92
> Duplicate of #35

Is there maybe a way we can support you, e.g. writing some code?

**Comment by chris9672** [comment] 2021-10-09 15:42
> 
> 
> I seem to have found a way (simple enough) to make an interface to C ++ classes for x64 and OpenCV 4.5.1. Now I'm testing ...
> 
> Duplicate of #138 Duplicate of #136 Duplicate of #102 Duplicate of #92 Duplicate of #35

When can we at least roughly expect an update? After all, it has now been almost a year.

**Comment by Laex** [comment] 2021-10-30 18:20
https://github.com/Laex/Delphi-OpenCV-Class

**Closed** 2021-10-30 18:25 UTC
