### ISSUE TITLE
[IDEA 💡] Publish as a package for Delphinus package manager.

### ISSUE THREAD

**Issue by Pawe1** [Laex/Delphi-OpenCV#94] opened 2017-10-06 13:53 UTC
**Delphinus** project: https://github.com/Memnarch/Delphinus

[:bulb: Here is some draft of integration :bulb:](https://github.com/Pawe1/Delphi-OpenCV/tree/Delphinus)

Regards
P.

**Comment by blaisexen** [comment] 2017-10-06 15:38
hi,
is this like Inno Setup?

**Comment by Pawe1** [comment] 2017-10-06 20:10
@blaisexen Nope. This is a package manager dedicated for Delphi (like GetIt) that supports repositories hostet at GitHub & Bitbucket.
It integrates with Delphi IDE by adding menu item.

![main screen](https://user-images.githubusercontent.com/22169532/31296020-1eb07dca-aae1-11e7-955e-f843ec74f2ff.png)

**It also supports package version dependencies** (in opposite to current GetIt implementation).
Authors of some popular libraries (like Spring4D, mORMot, OmniThreadLibrary, ...) use it as distribution channel for easy updates.

Because it uses GitHub API anyone can create and publish package without contacting Embarcadero and waiting :grinning: 
Also installing packages with Delphinus is a piece of cake - no more creating folders, no more editing search patches! :grin: Just clicking buttons.

Feel free to check it
There are 2 options:
* [Clone GitHub repository and compile it by yourself](https://github.com/Memnarch/Delphinus)
* [Use the Websetup](http://memnarch.bplaced.net/blog/pojects/all-downloads/?did=19)

https://github.com/Memnarch/Delphinus/wiki/Installing-Delphinus

**Comment by Laex** [comment] 2017-10-07 07:36
Duplicate of #77

**Comment by Pawe1** [comment] 2017-10-09 06:14
@Laex  oh... sorry xD
Feel free to delete it ;) [my stupidity...]

**Closed** 2017-10-09 07:05 UTC
